### ISSUE TITLE
About training model

### ISSUE THREAD

**Issue by J1ngZ112** [MiChaelinzo/Personalized-Content-Recommendations-using-Machine-Learning-and-Browser-History-Analysis#1]
Hello author, I am a beginner and would like to ask which machine learning models you used,thanks

**Comment by MiChaelinzo** [comment]
The machine learning model used is a collaborative filtering algorithm called Alternating Least Squares (ALS) matrix factorization. The ALS algorithm is a well-known matrix factorization technique used for recommendation systems, especially in situations where the data is sparse, and the matrix is large. The implementation uses the Spark MLlib library to train the ALS model on the user-item interaction data and generate personalized recommendations.
