### ISSUE TITLE
missing files in project

### ISSUE THREAD

**Issue by bocejo5** [MiChaelinzo/Personalized-Content-Recommendations-using-Machine-Learning-and-Browser-History-Analysis#2]
hi there!
I found your project very interesting but I cannot follow the readme installation tutorial because of there are not files mentioned.
Can you please add in your repo the missing files?
thank you so much

**Comment by MiChaelinzo** [comment]
Sorry I didn't complete the project I was too busy but you can use and look in the codes are pretty simple concept for a PCR ML, maybe I'll check again and work on it.

**Comment by MiChaelinzo** [comment]
But you can check this https://github.com/MiChaelinzo/Entra-Permission-Management-AI- I submitted this one for a [Entra Permissions Management Hackathon](https://entra-permissions-mgmt.devpost.com/)
